[package]
name = "clanker"
version = "0.3.0"
authors = ["Gregory Meyer <gregjm@umich.edu>"]
edition = "2018"
description = "Minimalistic command prompt for fish."
license = "MIT"
readme = "README.md"
repository = "https://github.com/Gregory-Meyer/clanker"

[dependencies]
colored = "^1.7.0"
dirs = "^1.0.5"
git2 = "^0.8.0"
libc = "^0.2.49"
nix = "^0.13.0"
unicode-segmentation = "^1.2.1"
whoami = "^0.4.1"

[[bin]]
name = "clanker-prompt"
path = "src/prompt.rs"

[[bin]]
name = "clanker-right-prompt"
path = "src/right_prompt.rs"

[[bin]]
name = "clanker-title"
path = "src/title.rs"
