[package]
name = "clanker"
version = "0.1.0"
authors = ["Gregory Meyer <gregjm@umich.edu>"]
edition = "2018"

[dependencies]
colored = "^1.7.0"
dirs = "^1.0.5"
git2 = "^0.8.0"
nix = "^0.13.0"
unicode-segmentation = "^1.2.1"
whoami = "^0.4.1"
